name: build docs PDF
on:
  push:
    branches: [ asf-site ]
  schedule:
  - cron: '*/30 * * * *'
jobs:
  build:
    name: publish PDF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python Env
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: generate PDF
      run: |
        bash .github/scripts/generate-pdf.sh